### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zsx2000** [zsx2000/sheduler#1]
- [ ] Sprawdzić lub zmienić dostawcę serwera do wysyłki maili (chyba nas zablokowali)
- [ ] Dodać logi
      - [ ] przy odczytywaniu pliku
      - [ ] przy wysyłce maila
      - [ ] przy starcie i wyłączeniu usługi
